<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)' == '' and '$(ArtifactsPath)' == ''">$(MSBuildProjectDirectory)/obj/</BaseIntermediateOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)/obj/**;$(MSBuildProjectDirectory)/bin/**</DefaultItemExcludes>
    <RuntimeIdentifiers>osx-arm64</RuntimeIdentifiers>
    <PublishSingleFile>false</PublishSingleFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(RestoreLockedMode)' == ''">true</RestoreLockedMode>
    <KalynaExpectedSignerSha256>BCA8E666BDC632C4A1C4BE0041B8677B820FF6F21C77BA9129E5809598295DE9</KalynaExpectedSignerSha256>
    <KalynaExpectedSignerSha3_512>0A040B673632E0B80AA9FA78FCD1466D26F22CBE1A182FDC7AE1A8ADCC892B2BF35F114222AE2B971F30DC67D4E89D31010DF37D87B7E09306DCB630AC60A7FB</KalynaExpectedSignerSha3_512>
    <KalynaExpectedSignerSkein1024>9184ED588F4D30EC2EFDD8D0757D8C8057E2ADBF42E786FA67999D7753049ABFD4BA287BB6B06564BB0E3B887D28A9D47A5698F902D4DF19003850B61EDEBA2A2D7682C5088341C95B5658890522F66507AA1E87705E03018BA8A5731FCF3B9B1A8945AC2BC9ACBC5769CE515E5F1401A0A34BD929CDB6B47E26D7170A1B469A</KalynaExpectedSignerSkein1024>
    <KalynaExpectedMldsa87Sha256>3FF927E3DE49ED41FBF82C7525348FC470EBECF6BA30F1F4A900DBC59CEAD0E5</KalynaExpectedMldsa87Sha256>
    <KalynaExpectedMldsa87Sha3_512>81646E966B53F2BB5780C2304A9C3C9563C66AD396CA8152CFCF3DBEE2821E119C4BD14634ADB574E4C5FF135F7FF90744B99356C441E942A282749BB5827001</KalynaExpectedMldsa87Sha3_512>
    <KalynaExpectedMldsa87Skein1024>A00579863E8165B40DDD5981200788FC56BAAD5BDB7DD1D824DA96FEA4449FE1508DDAA26A57970FF95EAD88C638498CA46FDD5CF4798D462E43290E9B3E47CA75A91AC757AC642C1A9FCA4DBFB26CAF635D7C01E0BF35FCC58BF2568FF997BC6AA94F069F59CC6888F398379EC4A92FAF12379FFAD20E688D35C8B19635E2FA</KalynaExpectedMldsa87Skein1024>
  </PropertyGroup>
</Project>
