<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)' == '' and '$(ArtifactsPath)' == ''">$(MSBuildProjectDirectory)/obj/</BaseIntermediateOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)/obj/**;$(MSBuildProjectDirectory)/bin/**</DefaultItemExcludes>
    <RuntimeIdentifiers>osx-arm64</RuntimeIdentifiers>
    <PublishSingleFile>false</PublishSingleFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(RestoreLockedMode)' == ''">true</RestoreLockedMode>
    <KalynaExpectedSignerSha256>3BCB7A3B1AF1EF8AEC07FA82FB00EF2CC10E558B5472116C99BD0822E9CC6A15</KalynaExpectedSignerSha256>
    <KalynaExpectedSignerSha3_512>1BECC0371994A56E0C4AB036AFC7CCAAB17665C4EFA3300A9FB31E4EDACE0E05253C3ADC535B1803479BE78D5C9B3C87740F58081D0977BB73369C6D04350056</KalynaExpectedSignerSha3_512>
    <KalynaExpectedSignerSkein1024>2ED4CCD6AD43C4185692676F7A57A6725A0AD3ED74A0648B97204EA92B7881D44E46CD49F75BD8B74147311C9397CDAF1FFCD4103DB65F30C5DD144F2EB455271A654A6CA67D062D562B3596553D27A254EB31DD7274AF52C8052A93618FD176D7A7FFCA3E22F50B7D45823322CC5705661E62065F53F78DBEFFC96D2DAE4DE6</KalynaExpectedSignerSkein1024>
    <KalynaExpectedMldsa87Sha256>1C5765A8C6FF176E03EFC1C2898F2032FE05A763A556405A52AA91C7C85C26E7</KalynaExpectedMldsa87Sha256>
    <KalynaExpectedMldsa87Sha3_512>FBE89108A5D1662A9EB02E33C113319D132A104674763D2DBEB7C13C2718A4FFD97290C61333E56D8B8C852BD0F10B5E5C83DAD6642DF14E423E6D234ADBB8D0</KalynaExpectedMldsa87Sha3_512>
    <KalynaExpectedMldsa87Skein1024>9F4686BE3FCDC6E92A591EFF5AF59B03A8822E8EF405CE94D3B11C8A6CEAF416772D8766D0E6B3572E72D92F4A50FFF0F5A70FD2E9144BEED3F312C02787E0553CDE48228A7A4009D360ED6E34D1EB2793FEF5A2FE0AD649967BC1E56F5C9895E7DFF7194AB4CF2425EC3DB36DDEF3CF7968EAD71F4BDF02D8C07CB631BC63A8</KalynaExpectedMldsa87Skein1024>
  </PropertyGroup>
</Project>
