<Project>
  <PropertyGroup>
    <KalynaSigningCertificateThumbprint>7BA65B5130F34AB9F15C0D074699D46D9BCCD21C</KalynaSigningCertificateThumbprint>
    <KalynaExpectedSignerSha256>D0C5454E2C122FFD03D6F265876468E3935537FF6BB312EEEE48D883A889CFBB</KalynaExpectedSignerSha256>
    <KalynaExpectedSignerSha3_512>642EA8DD52CC4ABF736C9E9E773F470B8862BF227B118596929D8200B7C1EE5EA7112E78BB6B637646E1555C6015737D5AAA2198B6B9BD135B28CD879A03EC2E</KalynaExpectedSignerSha3_512>
    <KalynaExpectedSignerSkein1024>2DE785DDE05787904F8EC13C9C7A0B9E76594F8BB4CAF3984D1EE15E667683CAFCFEC2F80CD1DF2000DFCE52DDE52594048967AFC1FCCBCF53F4DE84FDB486226FEB522EA72BC69088621845B5687D4FDBA79F2AA4F043B7CE01F703A037853E9D17BE273AB745AC8E811735CCE3538CB261C424F08FFFD166902848FB51DAA0</KalynaExpectedSignerSkein1024>
    <KalynaExpectedMldsa87Sha256>B3CF5B4465033351222AC5D6E1CC20F66432BB18AEC623EF76BB2C7823812219</KalynaExpectedMldsa87Sha256>
    <KalynaExpectedMldsa87Sha3_512>64F51E753DD04615FF31C1E7C804978F1AC3EDCDB8FF6FCFD76AD11E8187351E475A5A6A75D94D16363D474C317D4B7E058B8C60FC8E9E46A9E4D5D1563C778D</KalynaExpectedMldsa87Sha3_512>
    <KalynaExpectedMldsa87Skein1024>49B6D449163C38584C06D2793DDD47E7C6594056E419A73125FBE8088A2564C367A10526510B34588815171A59A09EF501A61F2F3E26D0001EF20E779CAD978545C4F1F25C74AE6AEB4BD1D45F94002831C623B50889C570B70D709859ACC2F6210959BAFC6FD1D78F57E259E353CD85BD46BFAEE8774B075C87A54953BDC3AC</KalynaExpectedMldsa87Skein1024>
  </PropertyGroup>
</Project>
