<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KalynaArchiver\KalynaArchiver.csproj" />
    <ProjectReference Include="..\KalynaArchiver.Signing\KalynaArchiver.Signing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\tools\zpaq.exe" Link="zpaq.exe" CopyToOutputDirectory="Always" />
    <None Include="..\tools\argon2.exe" Link="argon2.exe" CopyToOutputDirectory="Always" />
    <None Include="..\tools\kalyna_v12.dll" Link="kalyna_v12.dll" CopyToOutputDirectory="Always" />
    <None Include="..\tools\threefish_ref.dll" Link="threefish_ref.dll" CopyToOutputDirectory="Always" />
    <None Include="..\tools\argon2_ref.dll" Link="argon2_ref.dll" CopyToOutputDirectory="Always" />
    <None Include="..\tools\aes_ref.dll" Link="aes_ref.dll" CopyToOutputDirectory="Always" />
    <None Include="..\tools\mars_ref.dll" Link="mars_ref.dll" CopyToOutputDirectory="Always" />
    <None Include="..\tools\shacal2_ref.dll" Link="shacal2_ref.dll" CopyToOutputDirectory="Always" />
    <None Include="..\tools\chachapoly_ref.dll" Link="chachapoly_ref.dll" CopyToOutputDirectory="Always" />
    <None Include="..\tools\*.sha3" Link="%(Filename)%(Extension)" CopyToOutputDirectory="Always" />
    <None Include="..\tools\*.skein" Link="%(Filename)%(Extension)" CopyToOutputDirectory="Always" />
    <None Include="..\tools\*.khsig" Link="%(Filename)%(Extension)" CopyToOutputDirectory="Always" />
    <None Include="..\tools\mldsa87_ref.dll" Link="mldsa87_ref.dll" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>
